# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

def kwargsAcceptFun(**kwargs):
    # Print all key-value pairs
    for key, value in kwargs.items():
        print(f"{key}: {value}")


kwargsAcceptFun(city="Tashkent", temperature=25, humidity="60%")